name: "harbour" # Project Name

services:
  caddy:
    image: "lucaslorentz/caddy-docker-proxy:2.9"
    ports:
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
      - "80:80" # HTTP
    environment:
      - "CADDY_INGRESS_NETWORKS=caddy" # Exclusively Use Caddy Network
    labels:
      caddy.email: "${CADDY_EMAIL}" # Certificate Authority Email
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "caddy_config:/config"
      - "caddy_data:/data"
    networks:
      - "caddy"

  portainer:
    image: "portainer/portainer-${PORTAINER_EDITION}:lts" # Specify Edition
    labels:
      # User Interface
      caddy_0: "portainer.${PORTAINER_DOMAIN}"
      caddy_0.reverse_proxy: "{{upstreams http 9000}}"
      # Edge Agent
      caddy_1: "edge.${PORTAINER_DOMAIN}"
      caddy_1.reverse_proxy: "{{upstreams 8000}}"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - "caddy"

volumes:
  caddy_config:
  caddy_data:
  portainer_data:

networks:
  caddy:
    external: true
